### ISSUE TITLE
cfn-guard fails on rule files that do not end in a new line

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/aws-guard-rules-registry#207]
### What is the problem?

With the files in release 1.0.0, nist-1800-25.guard throws an error. This seems to be related to the last line being a new line or not 

```
~$ cfn-guard --version
cfn-guard 2.1.0
~$ cfn-guard validate --rules rules/nist-1800-25.guard --data templates/example.yaml
Parsing error handling rule file = nist-1800-25.guard, Error = Parser Error when parsing Parsing Error Error parsing file nist-1800-25.guard at line 2475 at column 1, when handling , fragment # Rule Intent: Checks that the access granted by the Amazon S3 bucket is restricted by any of the AWS principals, federated users, service principals, IP addresses, or VPCs that you provide.
---

~$ tail -n1  rules/nist-1800-25.guard
# Rule Intent: Checks that the access granted by the Amazon S3 bucket is restricted by any of the AWS principals, federated users, service principals, IP addresses, or VPCs that you provide.⏎
```

A way to fix this is to add a new line to the end of that file.

```
~$ echo "" >> rules/nist-1800-25.guard
~$ cfn-guard validate --rules rules/nist-1800-25.guard --data templates/example.yaml
```

There are probably multiple ways to fix this, some that come to mind:

- guard should not fail if the file does not end with a newline
- `build.py` could add a newline after each rule file (this seems a good idea anyway, in case a rule file does not start with a #)
- There could be a linting step / test to ensure that all files have a new line at the end.

### Reproduction Steps

see description

### What did you expect to happen?

I would expect the provided .guard files to not throw an error

### What actually happened?

There was an error

### CloudFormation Guard Version

2.1.0

### OS

MacOs

### OS Version

Montery - 12.4 (21F79)

**Comment by benbridts** [comment]
While looking into this, I also noticed that `build.py` can be slightly optimized (this is a nitpick, feel free to ignore):

This piece of code opens a file, using rule_set in the filename
```python
for build_file in glob.iglob(basedirectory, recursive=True):
  # [...]
  rule_set = data['ruleSetName']
  # [...]
  for rule in data['mappings']:
    control_list = ",".join(rule['controls'])
    guard_file = rule["guardFilePath"]
    custom_message = build_custom_message(rule_set, control_list)
    if check_build_skip(guard_file) is False:
      inputfile = open(guard_file).read()
      output_file_name = "./docker/output/" + rule_set + ".guard"
      outputfile = open(output_file_name, "a")
      outputfile.write(re.sub('<<', custom_message, inputfile, flags=re.M))
      outputfile.close()
  # [...]]
```

- Since `rule_set` is defined outside of the `for rule in data['mappings`]`, the file can be opened outside of the loop
- using `with` will also remove the need to close the handle: (which is not done for the input file in the current version of the code)

```python
for build_file in glob.iglob(basedirectory, recursive=True):
  # [...]
  rule_set = data['ruleSetName']
  # [...]
  with open(f"./docker/output/{rule_set}.guard", "a") as outputfile:
    for rule in data['mappings']:
      control_list = ",".join(rule['controls'])
      guard_file = rule["guardFilePath"]
      custom_message = build_custom_message(rule_set, control_list)
      if check_build_skip(guard_file) is False:
        with open(guard_file, "r") as inputfile:
          outputfile.write(re.sub('<<', custom_message, inputfile.read(), flags=re.M))
    # [...]]
```

**Comment by grolston** [comment]
It seems like the simple fix here would be to add a new line after each file is brought into the rule set to ensure this does not happen on other builds as well.

**Comment by grolston** [comment]
@benbridts added in the line break for the build to ensure all rule sets end with a new line break.
