### ISSUE TITLE
(docker): An older version of cfn-guard is included in the docker image

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/aws-guard-rules-registry#209]
### General Issue

An older version of cfn-guard is included in the docker image

### The Question

The current version of the docker image has an older version of cfn-guard, it would be nice to use the latest one

```
~$ cfn-guard --version
cfn-guard 2.1.0

~$ docker run -it public.ecr.aws/r7q6h7y6/guard:latest cfn-guard --version
cfn-guard 2.0.4
```

### CloudFormation Guard Version

n/a

### OS

n/a

**Comment by grolston** [comment]
Cargo currently isn't supporting the latest version. To update this we will need to change the install process and base image.

**Comment by grolston** [comment]
The current image leverages alpine while the github action is using an Ubuntu base image. I am proposing we change the image to Ubuntu to keep in parity and support cfn-guard installation as the same in testing.

**Comment by benbridts** [comment]
There is also a pre-build binary available (linux-x86_64-unknown-linux-musl), besides the source and ubuntu specific version (ubuntu-latest).

Using a pre-build binary might be another way to solve this (and it means you do not need rust in the container). If installing via cargo, it is worth considering if the `--locked` option is useful, or leads to more downsides.

**Comment by grolston** [comment]
It looks like the ubuntu 22.10 version slimmed it down a bit putting it around 80 MBs with cfn-guard installed. This supports latest version of cfn-guard and is similar to the CI testing environment for the testing done on the registry.

**Comment by mattvanstone** [comment]
@grolston do you plan to create a release for v1.0.1?

**Comment by grolston** [comment]
There will be a new release and published version here today.

**Comment by grolston** [comment]
There will be a new release and published version here today.

**Comment by grolston** [comment]
Image published to ECR and verified env path is working for cfn-guard. Current version is at
`cfn-guard 2.1.0`

Image is not based off ubuntu with a noticeable decrease in size of the image. I will publish a new release for 1.0.1 rule set to correspond with the rule set in the docker image.
