### ISSUE TITLE
Reports on: add to mapping yaml

### ISSUE THREAD

**Issue by brianterry** [aws-cloudformation/aws-guard-rules-registry#221]
### Description

Add `Reports on` to the mapping yaml. Today, `Reports on` resource types are only exposed in the header of the guard rule. This makes it difficult to see what resource types the rule will target. 

### Use Case

I would like to write an automated tool that leverages the rule, and I need  the `Reports on` resource type information. 

### Proposed Solution

Add `Reports on` to the mapping yaml

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by brianterry** [comment]
example
```
"mappings": [
    {
      "guardFilePath": "rules/aws/cloudtrail/cloud_trail_cloud_watch_logs_enabled.guard",
      "Reports on": AWS::Logs::LogGroup  
      "controls": [
        "section4a-govern-the-cloud-2-standard-workloads",
        "section4b-design-and-secure-the-cloud-11-material-workloads",
        "section4b-design-and-secure-the-cloud-14-material-workloads",
        "section4b-design-and-secure-the-cloud-14-standard-workloads",
        "section4c-run-the-cloud-3-standard-workloads",
        "section4c-run-the-cloud-5-standard-workloads"
      ]
    },
```

**Comment by grolston** [comment]
Switching this over from a mapping file stored directly in the repo to a resource mapping file that will be stored in a release. Within the build process a file will be created that pulls all the rules and creates a map file for rules and reportsOn. Putting this in the build will help ensure that all files are represented (those that are applicable).
