### ISSUE TITLE
Parsing error handling rule file

### ISSUE THREAD

**Issue by nitinitare** [aws-cloudformation/aws-guard-rules-registry#245]
### General Issue

yes

### The Question

![image](https://user-images.githubusercontent.com/35133782/233629819-39c7d58d-a56b-4886-bfbf-2e09611fd1c2.png)

I am running the cfn-guard validation command to test the cloudformation template but getting the error with multiple rules. Attaching the screenshot with the Parsing error handling rule file error message. Am I doing it in a wrong way or there is any issue with cfn-guard handling these rules files.

using command: cfn-guard validate -v --data cfn-template --rules ./aws-guard-rules-registry-1.0.2/rules/aws
where i have my template file in yaml format inside cfn-template folder. 

### CloudFormation Guard Version

2.1.3

### OS

Amazon Linux

### Other information

Running the command while build in AWS CodeBuild. was testing it for IAM policy and all the rules related to IAM policy were PASS. But not sure why this parsing error with other rule files.

**Comment by nitinitare** [comment]
Can anyone help on this issue?

**Comment by grolston** [comment]
Hi, have you downloaded the release rule sets and used the rule set files in there? Check out the releases and download the aggregated rule set files from there.

**Comment by grolston** [comment]
Take a look at [Using Guard Rules Registry](https://github.com/aws-cloudformation/aws-guard-rules-registry/blob/main/docs/Using-Guard-Rules-Registry.md) docs for examples.

**Comment by nitinitare** [comment]
> Hi, have you downloaded the release rule sets and used the rule set files in there? Check out the releases and download the aggregated rule set files from there.

Yes, did the same.


> Take a look at [Using Guard Rules Registry](https://github.com/aws-cloudformation/aws-guard-rules-registry/blob/main/docs/Using-Guard-Rules-Registry.md) docs for examples.

yes, followed the same.

**Comment by nitinitare** [comment]
@grolston, Any other suggestion. I am not sure if I am the only one facing this issue.

**Comment by grolston** [comment]
What is appears you are doing is using the cfn-guard command not as documented: 
You have `cfn-guard validate -v --data cfn-template --rules ./aws-guard-rules-registry-1.0.2/rules/aws`

Your rules you are using is the Guard rules directory and not a the compiled rules (it was not tested nor intended to be used like that in the raw form). When you download the release rules from [here](https://github.com/aws-cloudformation/aws-guard-rules-registry/releases/download/1.0.2/ruleset-build-v1.0.2.zip) and unzip the folder you will see files you can use in the output directory. For example, in there is a file named `NIST800-53Rev5.guard` if I use the command:

`cfn-guard validate -v --data cfn-template --rules ./NIST800-53Rev5.guard` 

it will test the template against the rules in the NIST800-53Rev5.guard file. 

If you are looking for testing against every rule (not recommended as you should have a plan for what your rule set should include), you an use the `guard-rules-registry-all-rules.guard` located in the output directory of the release.
